### Basic details
title: Supporting Docs
author: LIDA Data Analytics Team (DAT)
email: dat@leeds.ac.uk
description: Collection of guides

# baseurl: "/supporting-docs"
baseurl: ""
url: "https://curly-dollop-ywmw87e.pages.github.io"

### Site build settings
#theme: just-the-docs
# remote_theme: pmarsceill/just-the-docs
remote_theme: just-the-docs/just-the-docs

 
### License config
license: GNU GPLv3
license_url: https://www.gnu.org/licenses/gpl-3.0.html


callouts:
  important:
    title: Important
    color: blue
  warning:
    title: Warning
    color: red
  highlight:
    title: 
    color: yellow
  note:
    title: Note
    color: purple
